config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static#index"
  resources :spools
  resources :prints
end

app/models/print.rb
class Print < ApplicationRecord
  belongs_to :user
  belongs_to :spool

  validates :settings, :file, :print_name, :description, presence: true

  def is_owner?(test_user)
    user.id == test_user.id
  end
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_spools

  def index
    @prints = current_user.prints
  end

  def new
    @print = current_user.prints.build
  end

  def create
    @print = current_user.prints.build(print_params)
    if @print.save
      redirect_to prints_path
    else
      render :new
    end
  end

  def edit
    @print = Print.find(params[:id])
    unauthorized unless @print.is_owner?(current_user)
  end

  def update
    @print = Print.find(params[:id])
    if @print.is_owner?(current_user)
      if @print.update(print_params)
        redirect_to prints_path
      else
        render :edit
      end
    else
      unauthorized
    end
  end

  def destroy
    @print = Print.find(params[:id])
    if @print.is_owner?(current_user)
      @print.destroy

      redirect_to prints_path
    else
      unauthorized
    end
  end

  private
  def print_params
    params.require(:print).permit(:spool_id, :settings, :file, :success, :description, :print_name, :print_notes)
  end

  def get_spools
    @spools = current_user.spools
  end

  def unauthorized
    render file: "public/401.html", status: :unauthorized
  end
end

app/helpers/prints_helper.rb
module PrintsHelper
end

app/views/prints/_form.html.erb
<%= form_with model: print do |form| %>
  <%= form.label :spool %>
  <%= form.select :spool_id, options_for_select(@spools.map{ |s| ["#{s.manufacturer} #{s.material}", s.id]})%>
  <%= render "shared/form_errors", locals: {field: :spool_id, resource: print} %>

  <%= form.label :print_name%>
  <%= form.text_field :print_name%> 
  <%= render "shared/form_errors", locals: {field: :print_name, resource: print} %>

  <%= form.label :description %>
  <%= form.text_field :description %> 
  <%= render "shared/form_errors", locals: {field: :description, resource: print} %>

  <%= form.label :settings %>
  <%= form.text_field :settings %> <!-- TODO serialize the format used by cura and display in readable format -->
  <%= render "shared/form_errors", locals: {field: :settings, resource: print} %>

  <%= form.label :file %>
  <%= form.text_field :file %>
  <%= render "shared/form_errors", locals: {field: :file, resource: print} %>

  <%= form.label :success %>
  <%= form.check_box :success %>
  <%= render "shared/form_errors", locals: {field: :success, resource: print} %>

  <%= form.label :notes%>
  <%= form.text_field :notes%> 
  <%= render "shared/form_errors", locals: {field: :notes, resource: print} %>


  <%= form.submit %>
<% end %>

app/views/prints/_print_list_item.html.erb
<li>
  <%= print.print_name %> printed on <%= print.created_at %>
  <% if print.is_owner?(current_user) %>
    <%= link_to "Edit", edit_print_path(print) %>
    <%= link_to "Delete", print_path(print), method: :delete %>
  <% end %>
</li>

app/views/prints/edit.html.erb
<h2>Editing print created on <%= @print.created_at %></h2>

<%= render "form", print: @print, spools: @spools %>

app/views/prints/index.html.erb
<h2>Prints for <%= current_user.email %></h2>

<%= link_to "Start New Print", new_print_path %>
<ul class="prints">
  <% @prints.each do |print| %>
    <%= render "print_list_item", print: print %>
  <% end %>
</ul>

app/views/prints/new.html.erb
<h2>Creating a new spool for <%= current_user.email %></h2>

<%= render "form", print: @print, spools: @spools %>