config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static#index"
  resources :spools
  resources :prints
end

app/models/spool.rb
class Spool < ApplicationRecord
  belongs_to :user
  has_many :prints, dependent: :destroy

  validates :rfid, :material, :manufacturer, :purchased, presence: true

  def is_owner?(testuser)
    return user.id == testuser.id
  end
end

app/controllers/spools_controller.rb
class SpoolsController < ApplicationController
  before_action :authenticate_user!

  def index
    @spools = current_user.spools
  end

  def new
    @spool = current_user.spools.build
  end

  def create
    @spool = current_user.spools.build(spool_params)
    if @spool.save
      redirect_to spools_path
    else
      render :new
    end
  end

  def edit
    @spool = Spool.find(params[:id])
    unauthorized unless @spool.is_owner?(current_user)
  end

  def update
    @spool = Spool.find(params[:id])
    if @spool.is_owner?(current_user) 
      if @spool.update(spool_params)
        redirect_to spools_path
      else
        render :edit
      end
    else
      unauthorized
    end
  end

  def destroy
    @spool = Spool.find(params[:id])
    if @spool.is_owner?(current_user)
      @spool.destroy

      redirect_to spools_path
    else
      unauthorized
    end
  end

  private
  def spool_params
    params.require(:spool).permit(:rfid, :material, :manufacturer, :purchased)
  end

  def unauthorized
    render file: "public/401.html", status: :unauthorized
  end
end

app/helpers/spools_helper.rb
module SpoolsHelper
end

app/views/spools/_form.html.erb
<%= form_with model: spool do |form| %>
  <%= form.label :rfid %>
  <%= form.text_field :rfid %>
  <%= render "shared/form_errors", locals: { field: :rfid, resource: spool } unless spool.errors.empty? %>

  <%= form.label :manufacturer %>
  <%= form.text_field :manufacturer %>
  <%= render "shared/form_errors", locals: { field: :manufacturer, resource: spool } unless spool.errors.empty? %>


  <%= form.label :material %>
  <%= form.text_field :material %>
  <%= render "shared/form_errors", locals: { field: :material, resource: spool } unless spool.errors.empty? %>

  <%= form.label :purchased %>
  <%= form.date_field :purchased %>
  <%= render "shared/form_errors", locals: { field: :purchased, resource: spool } unless spool.errors.empty? %>

  <%= form.submit %>
<% end %>

app/views/spools/_spool_list.html.erb
<li>
  <%= spool.manufacturer %> <%= spool.material %> bought on <%= spool.purchased %>
  <%= link_to "Edit", edit_spool_path(spool) %>
  <%= link_to "Delete", spool_path(spool),
    method: :delete
  %>
</li>

app/views/spools/_spool_list_item.html.erb
<li>
  <%= spool.manufacturer %> <%= spool.material %> bought on <%= spool.purchased %>
  <% if spool.is_owner?(current_user) %>
    <%= link_to "Edit", edit_spool_path(spool) %>
    <%= link_to "Delete", spool_path(spool),
      method: :delete
    %>
  <% end %>
</li>

app/views/spools/edit.html.erb
<h2>Editing Spool for <%= current_user.email %></h2>

<%= render "form", spool: @spool %>

app/views/spools/index.html.erb
<h2>Spools for <%= current_user.email %></h2>

<%= link_to "Create New Spool", new_spool_path %>
<ul class="spools">
  <% @spools.each do |spool| %>
    <%= render "spool_list_item", spool: spool %>
  <% end %>
</ul>

app/views/spools/new.html.erb
<h2>New Spool for <%= current_user.email %></h2>

<%= render "form", spool: @spool %>